lastChangelogVersion: 15.10.8
setupVersion: 1
modelRoles:
  default: anthropic/claude-opus-4-8:low
  plan: openai-codex/gpt-5.6-terra:low
  slow: anthropic/claude-opus-5:high
  smol: anthropic/claude-haiku-4-5-20251001:xhigh
  designer: anthropic/claude-sonnet-5:low
  task: anthropic/claude-sonnet-5:low
  vision: openai-codex/gpt-5.4:low
