$font = Maple Mono NL NF

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 5
    noise = 0.0117
    contrast = 1.2
    brightness = 0.8
    vibrancy = 0.18
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = $TIME
    color = rgba(ebdcffff)
    font_size = 88
    font_family = $font
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    color = rgba(cdd6f4ff)
    font_size = 24
    font_family = Noto Sans
    position = 0, 70
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi wesbragagt
    color = rgba(a6e3a1ff)
    font_size = 20
    font_family = Noto Sans
    position = 0, -80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 56
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.2
    dots_center = true
    fade_on_empty = false
    font_color = rgba(cdd6f4ff)
    inner_color = rgba(1e1e2eb8)
    outer_color = rgba(cba6f7e6)
    check_color = rgba(a6e3a1e6)
    fail_color = rgba(f38ba8e6)
    placeholder_text = Password
    fail_text = $PAMFAIL
    rounding = 14
    position = 0, -150
    halign = center
    valign = center
}
