exec-once = dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target

$browser = zen-beta
$menu = rofi-freq
$mod = SUPER
$term = foot

animations {
  bezier = subtle, 0.16, 1, 0.3, 1
  animation = windows, 1, 5, subtle
  animation = windowsOut, 1, 5, subtle, slide
  animation = border, 1, 6, subtle
  animation = fade, 1, 6, subtle
  animation = workspaces, 1, 5, subtle, fade
  enabled = true
}

cursor {
  no_hardware_cursors = true
}

decoration {
  shadow {
    color = rgba(00000066)
    color_inactive = rgba(00000022)
    enabled = true
    range = 18
    render_power = 3
  }

  rounding = 8
}

general {
  border_size = 0
  col.active_border = rgba(00000000)
  col.inactive_border = rgba(00000000)
  gaps_in = 5
  gaps_out = 10
  layout = dwindle
}

input {
  scroll_factor = 0.6
  emulate_discrete_scroll = 1

  touchpad {
    disable_while_typing = false
    natural_scroll = false
    scroll_factor = 0.7
  }

  follow_mouse = 1
  kb_layout = us
  repeat_delay = 250
  repeat_rate = 40
}

bind = $mod, T, exec, $term
bind = $mod, B, exec, $browser
bind = $mod, E, exec, thunar
bind = $mod, Q, killactive,
bind = $mod, M, exit,
bind = $mod, Space, exec, $menu
bind = $mod, Escape, exec, loginctl lock-session
bind = $mod, F, fullscreen,
bind = $mod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = $mod SHIFT, V, togglefloating,
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, BackSpace, exec, waypaper
bind = $mod SHIFT, P, exec, grim -g "$(slurp -d)" - | swappy -f -
bind = $mod SHIFT, R, exec, wf-record
bind = $mod SHIFT, l, exec, kill -35 $(pgrep -fo nwg-dock)

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , F8, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , F7, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , F6, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,24

exec-once = [workspace 1 silent] foot
exec-once = [workspace 2 silent] zen-beta
exec-once = [workspace 5 silent] bitwarden
exec-once = [workspace 8 silent] obsidian
exec-once = wl-paste --watch cliphist store
exec-once = waybar
exec-once = nm-applet --indicator
exec-once = nwg-dock-hyprland -p bottom -lp end -i 36 -c rofi-freq -r
exec-once = swaync
exec-once = swww-daemon

monitor = eDP-1,preferred,auto,1

windowrulev2 = float, class:^(waypaper)$
windowrulev2 = size 900 600, class:^(waypaper)$
windowrulev2 = center, class:^(waypaper)$
windowrulev2 = animation fade, class:^(waypaper)$
windowrulev2 = opacity 0.7 0.7, class:^(waypaper)$
